/** @type {import('tailwindcss').Config} */
import animate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    spacing: {
      0: "0px",
      0.5: "2px",
      0.75: "3px",
      1: "4px",
      1.25: "5px",
      1.5: "6px",
      1.75: "7px",
      2: "8px",
      2.25: "9px",
      2.5: "10px",
      2.75: "11px",
      3: "12px",
      3.25: "13px",
      3.5: "14px",
      3.75: "15px",
      4: "16px",
      4.25: "17px",
      4.5: "18px",
      4.75: "19px",
      5: "20px",
      5.5: "22px",
      5.75: "23px",
      6: "24px",
      7: "28px",
      7.5: "30px",
      8: "32px",
      9: "36px",
      10: "40px",
      11: "44px",
      11.5: "46px",
      11.75: "47px",
      12: "48px",
      13.5: "54px",
      14: "56px",
      15: "60px",
      16: "64px",
      17: "68px",
      17.5: "70px",
      18: "72px",
      19: "76px",
      19.5: "78px",
      20: "80px",
      20.5: "90px",
      22: "88px",
      24: "96px",
      26: "104px",
      26.5: "106px",
      27: "108px",
      28: "112px",
      30: "120px",
      31: "124px",
      31.5: "126px",
      32: "128px",
      34: "136px",
      39.75: "159px",
      40: "160px",
      48: "192px",
      50: "200px",
      51: "204px",
      52.5: "210px",
      56: "224px",
      60: "240px",
      64: "256px",
      70: "280px",
      97.5: "390px",
      100: "400px",
      111: "444px",
      120: "480px",
      216: "864px",
      308: "1232px",
      320: "1280px",
    },
    screens: {
      lg: "1195px",
      md: "835px",
      sm: "770px",
    },
    lineHeight: {
      6: "24px",
      5: "20px",
      4.5: "18px",
    },
    fontSize: {
      h1: ["48px", "48px"],
      h2: ["30px", "36px"],
      h3: ["24px", "32px"],
      h4: ["20px", "28px"],
      p: ["16px", "28px"],
      blockquote: ["16px", "24px"],
      th: ["16px", "24px"],
      card: ["24px", "29px"],
      normal: ["14px", "20px"],
      9: "36px",
      7: "28px",
      5.25: "21px",
      4.5: "18px",
      3: ["12px", "20px"],
    },

    fontFamily: {
      inter: ["Inter", "Helvetica", "Arial", "sans-serif"],
    },
    extend: {
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      boxShadow: {
        "card-shadow": "0px 3.01px 3.01px 0px rgba(0, 0, 0, 0.25)",
      },
      fontWeight: {
        card: "900",
        h1: "800",
        th: "700",
        h2: "600",
        h3: "600",
        h4: "600",
        800: "800",
        600: "600",
        500: "500",
        p: "400",
        blockquote: "400",
      },
      backgroundImage: {
        "main-ton": "url('/src/assets/icons/icon-bg-ton.svg')",
        "main-web3": "url('/src/assets/icons/icon-bg-web3.svg')",
        purple: "linear-gradient(180deg, #141420 0.38%, #793DFF 200.07%)",
        "1-rank-gradient": "var(--gold-gradient)",
        "2-rank-gradient": "var(--silver-gradient)",
        "3-rank-gradient": "var(--bronze-gradient)",
        profit: "var(--profit-gradient)",
      },
      borderRadius: {
        0.5: "2px",
        0.75: "3px",
        1.5: "6px",
        2: "8px",
        2.5: "10px",
        3: "12px",
        3.325: "13.3px",
        3.5: "14px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
        10: "40px",
        16: "64px",
        50: "200px",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },

      colors: {
        inverse: "var(--inverse)",
        "card-before-start": "rgba(255, 255, 255, 0.27)",
        "card-before-end": "rgba(153, 153, 153, 0.03)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        text: "#F9FAFB",
        skyblue: "#0098EA",
        target: "	#22b458",
        menu: {
          item: {
            DEFAULT: "var(--menu-item)",
          },
        },
        "bg-accent": "var(--background-accent)",
        "share-button": "var(--share-button)",
        "share-text": "var(--share-color)",
        history: "var(--background-history-mobile)",
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "#783cff",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
          "accent-foreground": "var(--muted-accent-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        "background-coin-select": "var(--background-coin-select)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar-background)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        white: "#f9fafb",
      },
    },
  },

  plugins: [animate],
};
