export const DATA_PROFILE_PAGE = {
  en: {
    title: "Profile",
    titleError: "The profile is temporarily unavailable",
    totalBet: "Total Bet",
    totalWin: "Total Win",
    balance: "balance",
    share: "Share",
    profile: "Profile",
    walletAddress: "Wallet Address",
    getExperience: "How to get experience?",
    level: "Level",
    textButton: "Got it",
    betAmount: "Bet amount",
    expAmount: "Experience amount",
    profileEmpty: "Start playing and it will show up",
    button_copy: "Copy",
    copied: "Copied",
  },
  ru: {
    title: "Профиль",
    titleError: "Профиль временно недоступен",
    totalBet: "Общая сумма ставок",
    totalWin: "Общий выигрыш",
    balance: "Баланс",
    share: "Поделиться",
    profile: "профилем",
    walletAddress: "Адрес кошелька",
    getExperience: "Как получить опыт",
    level: "Уровень",
    textButton: "Понятно",
    betAmount: "Сумма ставки",
    expAmount: "Опыт",
    profileEmpty: "Начните играть, и он появится",
    button_copy: "Скопировать",
    copied: "Скопировано",
  },
};
